
local FORUMADDR = minetest.settings:get("forum_topic")
if not FORUMADDR or FORUMADDR == "" then
	FORUMADDR = "forum.minetest.net"
end

shout.BUILTIN_HINTS = {
	"You can ignore players who create drama or ruin chat by using the chat-filter interface, accessed through the Key of Citizenship.",
	"Mobs sometimes place blocks in protected areas. This is not griefing, because the blocks are not protected. Anyone may remove them.",
	"You may use the '/r <message>' command to quickly reply via PM to the last player to send you a PM.",
	"Strenuous activity increases your exhaustion and therefore hunger over time. This includes swimming, mining, or sprinting.",
	"Fallen blocks can be dug by anyone, even in protected areas.",
	"Use /channel to join a group PM channel, and /x to communicate to the channel's members.",
	"Stamina comes back faster when you are not hungry and resting in one place.",
	"Use the /players command when part of a group PM channel to see others on your channel.",
	"The ID Marker item hides your name, and obfuscates the public bones report when you die or pick bones.",
	"Most plants grow poorly near ice. Some plants won't grow at all.",
	"You can test protection without harming yourself by punching nodes with a stick.",
	"Falling nodes dropped above farms and gardens will do no damage to protected plants.",
	"Use teleports, gateways, and flameportals to get around quickly.",
	"Place city marker blocks to mark your land as part of the city, to help suppress unwanted PvP.",
	"Some rare foods heal hearts immediately. You may prefer to save these for combat situations.",
	"Most trees will refuse to grow underground. Firetrees do not suffer this limitation.",
	"You can get information about a node using the node inspector tool.",
	"To maintain your account, always keep a passport token (Proof or Key) in your main inventory.",
	"Prevent griefing by protecting your structures. Serious builders are advised to protect the land around their builds as well.",
	"Protect your bases to prevent griefing by others.",
	"Protection stops most types of environment damage, but does not prevent damage from lava.",
	"Certain blocks are vulnerable to lava griefing even when protected, such as stone and cobble.",
	"Certain foods refresh stamina, and can be used to give your avatar an extra endurance boost.",
	"Passive healing is very slow for serious injuries, but quick for light wounds.",
	"Travel speed is affected by the surfaces you travel on. Prefer using roads and avoid deep snow.",
	"Flowers, plants, and saplings can be found in the deep wastes far from the city.",
	"Use the /mapfix command to correct issues with lighting or liquid flow. See /help mapfix.",
	"Lava does not respect protection and is very dangerous!",
	"You can place water for farms above sea level by melting ice with torches or fire.",
	"You can travel over flat snow or ice quickly using a sled.",
	"Icemen are the primary source of mossy cobble, which is used as a fuel in some teleports.",
	"You can place a public bed in city areas (not ownable by anyone) by holding 'E' when you place it.",
	"You can place nearly any block as a falling node by holding 'E' when you place it, with air below.",
	"The brimstone ocean contains a few resources not found anywhere else; however the entire underworld is very dangerous.",
	"Locked chests are unlocked (and items may be stolen) if the chest lid is open.",
	"When you die, sometimes your bones are placed in odd places. Look around very carefully before giving up.",
	"Starvation will drain your health down to half a heart, but will not kill you.",
	"Sleep in a bed regularly to keep your respawn position from expiring after death.",
	"Use bandages to keep your health full. Stamina and hunger will benefit.",
	"Being hurt reduces your ability to sprint and jump.",
	"Prefer traveling by road or teleport when possible for faster transit times.",
	"Your speech is published live on channel 40,000. Please do not swear.",
	"Bonebox deployment is part of this adventure.",
	"Information-latency can be a nuisance.",
	"A diving helmet and canisters of compressed air will allow you to stay underwater longer.",
	"Lava causes strong, localized convection currents.",
	"Water is wet.",
	"Beware the guards of the Deep.",
	"This is a useless message.",
	"Obsidian Gateways and Flameportals are fragile methods of transportation. Protect them!",
	"This is a confused message.",
	"This message doesn't have any meaning.",
	"Pay no attention to the man behind the curtain.",
	"Shears and silver picks can sometimes be used to obtain materials or resources that other tools cannot.",
	"Walk softly and carry a big stick.",
	"Punching an itemframe or pedestal with a stick will restore missing item entities.",
	"Items placed in itemframes or pedestals may occasionally become invisible. Punch with a stick to restore them.",
	"Dry shrubs and torches (lit or not) may be crafted into sticks.",
	"New player short on fuel? You can burn wooden armor in stone furnaces.",
	"That's a Waitabit Tree. Don't go near a Waitabit Tree. They grab you.",
	"Most trees are sensitive to cold conditions and may refuse to grow. The Firetree is particularly ornery.",
	"All positions printed in server chat are realm-local.",
	"Found a bug? You can send in-game email to <" .. utility.get_admin_name() .. "> to report it.",
	"This sentence is false.",
	"You can send game-balance suggestions to <" .. utility.get_admin_name() .. "> using the in-game email system.",
	"Mr. Momoa, your trailer's on fire.",
	"You can use a trade booth to buy and sell items remotely, for shops set up to support it.",
	"If you get stuck somewhere, you can use /emergency_recall to get out. But beware its cost.",
	"Nothing responding? That's because I'm AFK!",
	"In case the server is unreachable, be sure to check http://" .. FORUMADDR .. " for updates.",
	"Have a gripe or a doubt? Feel free to speak out at http://" .. FORUMADDR .. ". No spam, please.",
}
