
-- Localize for performance.
local vector_distance = vector.distance
local vector_round = vector.round
local vector_add = vector.add
local vector_equals = vector.equals
local math_random = math.random
local CITYBLOCK_DELAY_TIME = city_block.CITYBLOCK_DELAY_TIME
local time_active = city_block.time_active

local FORMTABLE = {
	-- Generated by formspec editor V1.
	size = {x=10.7, y=6.7},
	children = {
		{slot_bg_hover="#5A5A5A", slot_bg_normal="#00000069", slot_border="#141318", tooltip_bgcolor="#30434C", tooltip_fontcolor="#FFF", type="listcolors"},
		{h=6.7, texture="gui_formbg.png", type="background9", w=10.7, x=0, x1=50, y=0},
		{type="container", x=0.5, y=0.5},
		{h=0.4, text="Enter city/area region name:", type="label", w=4.5, x=0, y=0},
		{close_on_enter=true, default="", h=0.8, label="", name="CITYNAME", type="field", w=3.6, x=0, y=0.4},
		{h=0.4, label="Confirm", name="OK", type="button_exit", w=1.6, x=3.7, y=0.4},
		{h=0.4, label="Abort", name="CANCEL", type="button_exit", w=1.6, x=3.7, y=0.8},
		{type="container_end"},
		{type="container", x=0.5, y=3.5},
		{label="Mark Dueling Arena", name="pvp_arena", selected="true", type="checkbox", x=0, y=0},
		{label="Signal Nearby Keys", name="hud_beacon", selected=true, tooltip="Toggle whether to show a HUD beacon on nearby Citizenship Keys.", type="checkbox", x=0, y=0.4},
		{label="Allow Protectors", name="allow_protectors", selected=true, tooltip="Control whether users may place protectors near.", type="checkbox", x=0, y=0.8},
		{type="container_end"},
		{type="container", x=4.76, y=3.37},
		{FORMID="configlist", h=1, inventory_location="current_player", list_name="craft", type="list", w=1, x=0, y=0},
		{h=1, texture="configurator_inv.png", type="image", w=1, x=0, y=0},
		{type="container_end"},
		{h=1, inventory_location="current_player", list_name="main", type="list", w=8, x=0.5, y=5.1},
		{h=0.8, label="Manage Claims", name="manage_claims", style={bgcolor="brown"}, tooltip="Borough Administration", type="button_exit", w=2.4, x=7.9, y=0.9},
		{color="#aaaaaa", h=4.4, type="box", w=0.1, x=7.5, y=0.4},
		{h=0.34, text="Mayor Admin:", type="label", w=2.35, x=7.9, y=0.5},
	},
}



function city_block.create_formspec(pos, pname, blockdata)
	local meta = minetest.get_meta(pos)
	local inv = meta:get_inventory()
	local spos = pos.x .. "," .. pos.y .. "," .. pos.z

	local guiobj = formspec.create_gui_object(FORMTABLE)
	guiobj:get_control_by_id("configlist").inventory_location = "nodemeta:" .. spos
	guiobj:get_control_by_id("configlist").list_name = "config"
	guiobj:get_control_by_name("CITYNAME").default = blockdata.area_name

	-- Create inventory if needed.
	if inv:get_size("config") == 0 then
		inv:set_size("config", 1)
	end

	guiobj:get_control_by_name("pvp_arena").selected = (blockdata.pvp_arena == true)
	guiobj:get_control_by_name("hud_beacon").selected = (blockdata.hud_beacon == true)
	guiobj:get_control_by_name("allow_protectors").selected = (blockdata.allow_protectors == nil or blockdata.allow_protectors == true)

	return guiobj:to_formspec()
end



local function check_cityname(cityname)
  return not string.match(cityname, "[^%a%s]")
end



function city_block.on_receive_fields(player, formname, fields)
	if formname ~= "city_block:main" and formname ~= "city_block:mayor" then
		return
	end
	if not player or not player:is_player() then
		return
	end

	local pname = player:get_player_name()
	local pos = city_block.formspecs[pname]
	local block = city_block.get_block(pos)

	-- Context should have been created in 'on_rightclick'. CSM protection.
	if not pos then
		return true
	end

	-- Ensure we got the city block data.
	if not block then
		return true
	end

	local meta = minetest.get_meta(pos)
	local owner = meta:get_string("owner")

	-- Form sender must be owner.
	if pname ~= owner then
		return true
	end

	if fields.manage_claims then
		local is_admin = gdac.player_is_admin(pname)

		if is_admin or xp.get_xp(pname, "buildxp") >= city_block.BUILDXP_FOR_MAYOR then
			if is_admin or os.time() > city_block.BOROUGH_MIN_ACTIVATION_TIME then
				local formspec = city_block.create_mayor_formspec(pos, pname, block)
				minetest.show_formspec(pname, "city_block:mayor", formspec)
				core.log("action", ("[cityblock] <%s> gained access to mayoral functions at %s."):
					format(pname, minetest.pos_to_string(pos)))
			else
				minetest.chat_send_player(pname,
					("This feature is not available until %s.")
					:format( os.date("!%Y/%m/%d", city_block.BOROUGH_MIN_ACTIVATION_TIME) )
				)
			end
		else
			core.log("info", ("[cityblock] <%s> was refused access to mayoral functions at %s."):
				format(pname, minetest.pos_to_string(pos)))
			minetest.chat_send_player(pname,
				("# Server: You need %d Build XP to access this function.")
				:format(city_block.BUILDXP_FOR_MAYOR))
		end
		return true
	end

	if formname == "city_block:mayor" then
		city_block.on_mayor_fields(player, formname, fields)
		return true
	end

	if fields.key_enter_field == "CITYNAME" or fields.OK then
		local area_name = (fields.CITYNAME or ""):trim()
		area_name = area_name:gsub("%s+", " ")

		-- Ensure city name is valid.
		local is_valid = true

		-- Empty area name means erase.
		--[[
		if #area_name == 0 then
			is_valid = false
		end
		--]]

		if #area_name > 20 then
			is_valid = false
		end
		if not check_cityname(area_name) then
			is_valid = false
		end

		if anticurse.check(pname, area_name, "foul") then
			is_valid = false
		elseif anticurse.check(pname, area_name, "curse") then
			is_valid = false
		end

		if not is_valid then
			minetest.chat_send_player(pname, "# Server: Region name not valid.")
			return
		end

		-- Write out.
		meta:set_string("cityname", area_name)
		meta:set_string("infotext", city_block.get_infotext(pos))

		if #area_name > 0 then
			block.area_name = area_name
		else
			block.area_name = nil
		end

		city_block:save()
	end

	if fields.pvp_arena == "true" then
		block.pvp_arena = true
		meta:set_string("infotext", city_block.get_infotext(pos))
		city_block:save()
	elseif fields.pvp_arena == "false" then
		block.pvp_arena = nil
		meta:set_string("infotext", city_block.get_infotext(pos))
		city_block:save()
	end

	if fields.hud_beacon == "true" then
		block.hud_beacon = true
		city_block:save()
	elseif fields.hud_beacon == "false" then
		block.hud_beacon = nil
		city_block:save()
	end

	if fields.allow_protectors then
		local str = fields.allow_protectors
		if str == "true" then
			block.allow_protectors = true
		elseif str == "false" then
			block.allow_protectors = false
		end
		city_block:save()
	end

	if fields.quit then
		city_block.formspecs[pname] = nil
		city_block.guiobjs[pname] = nil
		return true
	end

	return true
end
